# Change these first
owner: Nexirift # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Nexirift (Primary)
    url: https://nexirift.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nexirift.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Nexirift Status
  introTitle: Status page for Nexirift
  introMessage: This is a status page for Nexirift, a decentralized social media platform.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
